name = "edge-api-signup"
main = "src/index.ts"
compatibility_date = "2023-09-18"


[vars]
ENVIRONMENT = "prod"
DATABASE_HOST = "us-west.connect.psdb.cloud"
DATABASE_NAME = "fawlmain"
DATABASE_USERNAME = "zj5jyr4wqps4xfaiviy5"